const Props = require("./t");

const props = {
  div: Props.HTMLAttributes,
  a: Props.AnchorHTMLAttributes,
  area: Props.AreaHTMLAttributes,
  base: Props.BaseHTMLAttributes,
  blockquote: Props.BlockquoteHTMLAttributes,
  button: Props.ButtonHTMLAttributes,
  canvas: Props.CanvasHTMLAttributes,
  col: Props.ColHTMLAttributes,
  colgroup: Props.ColgroupHTMLAttributes,
  data: Props.DataHTMLAttributes,
  details: Props.DetailsHTMLAttributes,
  del: Props.DelHTMLAttributes,
  dialog: Props.DialogHTMLAttributes,
  embed: Props.EmbedHTMLAttributes,
  fieldset: Props.FieldsetHTMLAttributes,
  form: Props.FormHTMLAttributes,
  html: Props.HtmlHTMLAttributes,
  iframe: Props.IframeHTMLAttributes,
  img: Props.ImgHTMLAttributes,
  ins: Props.InsHTMLAttributes,
  input: Props.InputHTMLAttributes,
  keygen: Props.KeygenHTMLAttributes,
  label: Props.LabelHTMLAttributes,
  li: Props.LiHTMLAttributes,
  link: Props.LinkHTMLAttributes,
  map: Props.MapHTMLAttributes,
  menu: Props.MenuHTMLAttributes,
  audio: Props.AudioHTMLAttributes,
  meta: Props.MetaHTMLAttributes,
  meter: Props.MeterHTMLAttributes,
  q: Props.QuoteHTMLAttributes,
  object: Props.ObjectHTMLAttributes,
  ol: Props.OlHTMLAttributes,
  optgroup: Props.OptgroupHTMLAttributes,
  option: Props.OptionHTMLAttributes,
  output: Props.OutputHTMLAttributes,
  param: Props.ParamHTMLAttributes,
  progress: Props.ProgressHTMLAttributes,
  slot: Props.SlotHTMLAttributes,
  script: Props.ScriptHTMLAttributes,
  select: Props.SelectHTMLAttributes,
  source: Props.SourceHTMLAttributes,
  style: Props.StyleHTMLAttributes,
  table: Props.TableHTMLAttributes,
  textarea: Props.TextareaHTMLAttributes,
  td: Props.TdHTMLAttributes,
  th: Props.ThHTMLAttributes,
  time: Props.TimeHTMLAttributes,
  track: Props.TrackHTMLAttributes,
  video: Props.VideoHTMLAttributes,
};

module.exports = {
  props,
};
